version: '3.1'

services:

  spigot-dockerized:
    image: spigot-dockerized

    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        JAVA_VERSION: "${JAVA_VERSION:-16}"

    ports:
      - "${PORT:-25565}:25565"

    environment:
      VERSION: "${VERSION:-1.17}"
      MEMORY_MAX: "${MEMORY_MAX:-2048M}"
      MEMORY_MIN: "${MEMORY_MIN:-512M}"
      EULA: "${EULA:-false}"

    volumes:
      - "${SERVER_DIRECTORY:-/opt/minecraft-server}:/opt/minecraft-server"
